name: Fetch and Commit Data

on:
  schedule:
    - cron: '*/1 * * * *'  # 1分ごとに実行

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: データを取得
        run: |
          curl -sL "https://clouddata-srev.kothn.net/rooms" -o data.json

      - name: 変更を確認してコミット
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Update data.json"
          git push
